# no version needed since 2020
services:
  jekyll:
    image: bretfisher/jekyll-serve
    container_name: eateries
    working_dir: /srv-jekyll
    volumes: 
      - .:/srv-jekyll
    ports:
      - '5743:5743'
      - '35743:35743'
    command: |
      bundle exec jekyll serve
      --trace --force_polling
      --host 0.0.0.0
      --port 5743
      --livereload
      --livereload-port 35743
